apiVersion: v1
kind: Service
metadata:
  name: blog-server
spec:
  selector:
    name: blog-server
  ports:
  - port: 10010
    targetPort: 8000
    nodePort: 30010
    protocol: TCP
    name: django
  - port: 10011
    targetPort: 8888
    nodePort: 30011
    protocol: TCP
    name: jupyter
  externalIPs:
  - 192.168.0.21
  - 192.168.0.22
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: blog-server
    spec:
      hostname: blog-server
      containers:
      - name: db-server
        image: mysql:5.7
        env: 
        - name: MYSQL_DATABASE
          value: django
        - name: MYSQL_USER
          value: apiadmin
        - name: MYSQL_PASSWORD
          value: apiadmin_pwd
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/mysql
      - name: ap-server
        image: pshost02:5000/blog/apserver:1.0
        ports:
        - containerPort: 8000
          name: django
        - containerPort: 8888
          name: jupyter
        volumeMounts:
        - name: ap-volume
          mountPath: /opt
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: blog-dev-db
        - name: ap-volume
          persistentVolumeClaim:
            claimName: blog-dev-ap
