apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-dev-db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/kube/volumes/blog-dev-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-dev-ap
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/kube/volumes/blog-dev-ap
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-dev-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-dev-ap
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

